<a href="https://colab.research.google.com/github/ujeongmin/ESAA/blob/main/ESAA_HW_9_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [CH2 사이킷런으로 시작하는 머신러닝]
### 01. 사이킷런 소개와 특징
* 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리
* 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향할 정도로 쉽고 가장 파이썬스러운 API 제공
* 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API 제공
* 오랜 기간 실전 환경에서 검증됨, 성숙한 라이브러리

In [1]:
pip install scikit-learn

In [2]:
import sklearn
print(sklearn.__version__)       # 교재는 0.19.1 기반

1.2.2




---


### 02. 첫번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기
* 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 Feature 기반

#### 분류 (Classification)
* 대표적인 지도학습 방법의 하나
* 지도학습은 학습을 위한 다양한 피처와 분류 결정값인 레이블(Label) 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측
> 이 때 학습을 위해 주어진 데이터 세트를 학습 데이터 세트  
> 머신러닝 모델의 예측 성능을 평가하기 위해 주어진 데이터 세트를 테스트 데이터 세트

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

* sklearn.tree : 트리 기반 ML 알고리즘을 구현한 클래스의 모임
* sklearn.model_selection : 학습 데이터, 검증 데이터, 예측 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 다양한 모듈의 모임

In [ ]:
import pandas as pd

# 붓꽃 데이터 세트를 로딩
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris.tartget은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

* 피처에는 sepal length, sepal width, petal length, petal width가 있음
* 레이블은 0,1,2 세가지 값으로 되어있으며 0이 Setosa 품종, 1이 versicolor 품종, 2가 virginica 품종 의미

#### 학습용, 테스트용 데이터 분리
* train_set_split() API 이용
> test_size=0.2로 입력 파라미터를 설정하면 전체 중 20%가 테스트 데이터, 80%가 학습 데이터로 분할됨

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

* iris_data : 피처 데이터 세트
* iris_label : 레이블 데이터 세트
* test_size : 전체 데이터 세트 중 테스트 데이터의 비율
* random_state : 수행할 때 마다 동일한 데이터 세트로 분리하기 위해 일정한 숫자 값으로 부여 (숫자는 어떤 값을 지정해도 상관 없음)
> train_test_split()은 데이터를 무작위로 분리하므로 이걸 지정하지 않으면 수행할 때마다 다른 학습, 테스트용 데이터를 만들 수 있음

#### 학습 데이터를 기반으로 의사 결정 트리를 이용해 학습과 예측을 수행
* DecisionTreeClassifier 객체와 fit() 메서드로 학습 수행
> 객체.fit(학습용 피처 데이터, 결정값 데이터 세트)

In [ ]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

* 학습 완료됐으므로 객체와 predict() 메서드로 예측 수행
> 예측은 학습 데이터가 아닌 다른 데이터를 이용해야함(즉 테스트 데이터 세트 이용)


In [ ]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

#### 예측 성능 평가
* 정확도 측정
> 예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지 평가하는 지표
* accuracy_score() 함수 사용
> accuracy_score(실제 레이블 데이터 세트, 예측 레이블 데이터 세트)

In [ ]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))            # 예측 정확도 93.33%로 측정됨

예측 정확도: 0.9333


#### 프로세스 정리
1. 데이터 세트 분리 : 학습, 테스트 데이터로 분리
2. 모델 학습 : 학습 데이터로 ML 알고리즘 적용해 모델 학습
3. 예측 수행 : 학습된 모델로 테스트 데이터의 분류 예측
4. 평가 : 예측값과 테스트 데이터의 실제값과 비교해 ML 모델 성능 평가



---

### 03. 사이킷런의 기반 프레임워크 익히기

#### Estimator 이해 및 fit(), predict() 메서드
* 분류 알고리즘을 구현한 클래스 Classifier & 회귀 알고리즘을 구현한 클래스 Regressor -> 합쳐서 Estimator 클래스
* 지도학습의 모든 알고리즘을 구현한 클래스를 통칭해서 Estimator라고 부름

#### 내장된 예제 데이터 세트

* 분류와 클러스터링을 위한 표본 데이터 생성기
> datasets.make_classifications() : 분류를 위한 데이터 세트 만듬  
> datasets.make_blobs() : 클러스터링을 위한 데이터 세트를 무작위로 생성해 줌
* 키는 보통 아래와 같이 구성되어 있음
> data : 피처의 데이터 세트  
> target : 분류 시 레이블 값  
> target_names : 개별 레이블의 이름  
> feature_names : 피처의 이름  
> DESCR : 데이터 세트에 대한 설명과 각 피처의 설명

In [ ]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))           # Bunch 클래스는 딕셔너리 자료형과 유사함

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('\n feature_names 의 type:', type(iris_data.feature_names))
print(' feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names 의 type:', type(iris_data.target_names))
print(' target_names 의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type:', type(iris_data.data))
print(' data 의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:', type(iris_data.target))
print(' target 의 shape:', iris_data.target.shape)
print(iris_data.target)


 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
 target_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.



---

### 04. Model Selection 모듈 소개
#### 학습/테스트 데이터 세트 분리 - train_test_split()
* 다음은 학습과 예측을 동일한 데이터 세트로 수행한 결과

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0


* 정확도가 100%가 됨, 이미 학습한 데이터 세트를 기반으로 예측했기 때문
> 답을 알고 있는 상태에서 똑같은 문제가 출제된 것
* 따라서 예측을 수행하는 데이터 세트는 전용의 테스트 데이터 세트여야 함

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

* train_test_split()을 이용해 테스트 데이터를 30%, 학습 데이터를 70%로 분리

In [4]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


#### **교차 검증**
* 앞선 부분은 과적합에 취약한 약점 가질 수 있음
* 과적합 : 학습 데이터에만 과도하게 최적화되어 실제 예측을 실제 데이터로 수행할 경우 예측 성능이 과도하게 떨어짐
* 교차 검증
> 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행함  
> 본고사를 치르기 전에 모의고사를 여러 번 보는 것과 비슷

#### 1) K 폴드 교차 검증
* K개의 데이터 폴드 세트를 만들어서 K번 만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행하는 방법
* 학습 데이터 세트와 검증 데이터 세트를 점진적으로 변경하면서 1번째부터 마지막 K번째까지 학습과 검증을 수행
> 학습/학습/학습/검증  
> 학습/학습/검증/학습 ...

In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


* kfold = KFold(n_splits=5)로 KFold 객체 생성했음
* 객체의 split()을 호출해 전체 데이터를 5개의 폴드 데이터 세트로 분리함 (학습은 4/5인 120개, 테스트는 1/5인 30개로 분할됨)

In [6]:
n_iter = 0

# KFold 객체의 split()을 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1
  # 반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'
         .format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 데이터 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기:120, 검증 데이터 크기:30
#1 검증 데이터 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기:120, 검증 데이터 크기:30
#2 검증 데이터 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기:120, 검증 데이터 크기:30
#3 검증 데이터 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기:120, 검증 데이터 크기:30
#4 검증 데이터 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기:120, 검증 데이터 크기:30
#5 검증 데이터 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


* 5번 교차 검증 결과 평균 검증 정확도는 0.9
* 교차 검증 시마다 검증 세트의 인덱스가 달라짐 (각각 30개씩 검증 세트 인덱스 생성)

#### 2) Stratified K 폴드
* 불균형한 분포도를 가진 레이블 데이터 집합을 위한 K 폴드 방식
> 특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한쪽으로 치우치는 집합을 말함  
>  ex) 대출 사기 데이터 : 대부분은 정상 대출, 아주 적은 건수가 사기 대출 (건수는 작지만 대출 사기 예측을 위한 매우 중요한 데이터 세트임)

In [7]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [10]:
kfold = KFold(n_splits=3)              # 50개씩 3개였으므로 3개의 폴드 세트 생성
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())
  iris_df['label'].value_counts()

## 교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


* 첫 번째 교차 검증 : 학습 레이블 1,2 / 검증 레이블 0
> 0의 경우는 전혀 학습하지 못함, 그러므로 학습 모델은 0을 예측하지 못함
* 이런 레이블 값의 분포도를 반영하지 못하는 문제를 StratifiedKfold가 해결해 줌

In [11]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


* 학습 레이블과 검증 레이블의 데이터 값의 분포도가 동일하게 할당됨
* 이렇게 분할이 되어야 레이블 값 0,1,2를 모두 학습할 수 있고, 이에 기반해 검증을 수행할 수 있음

In [12]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  # 반복 시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'
         .format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 데이터 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 :0.98, 학습 데이터 크기:100, 검증 데이터 크기:50
#1 검증 데이터 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기:100, 검증 데이터 크기:50
#2 검증 데이터 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기:100, 검증 데이터 크기:50
#3 검증 데이터 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


* Stratified K 폴드의 경우 원본 데이터의 레이블 분포도의 특성을 반영한 학습 및 검증 데이터 세트를 만들 수 있음
* 왜곡된 레이블 데이터 세트에서는 반드시 Stratified K 폴드를 이용해 교차 검증해야 함

#### 교차 검증을 보다 간편하게 - cross_val_score()
* 아래의 과정을 한꺼번에 수행해주는 API
* KFold 과정 : 폴드 세트를 설정 > for 루프에서 반복으로 학습 및 테스트 데이터의 인덱스 추출 > 반복적으로 학습과 예측을 수행하고 예측 성능 반환
* cross_val_score(estimator, X, y, scoring, cv)
> estimator : Classifier 또는 Regressor  
> X : 피처 데이터 세트  
> y : 레이블 데이터 세트  
> scoring : 예측 성능 평가 지표를 기술  
> cv : 교차 검증 폴드 수  
> classifier 입력되면 Stratified K 폴드 방식, regressor 입력되는 K 폴드 방식으로 분할함

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring = 'accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


* cross_val_score()는 cv로 지정된 횟수만큼 scoring 파라미터로 지정된 평가 지표로 평가 결괏값을 배열로 반환
* 비슷한 API로 cross_validate()가 있음, 이건 여러 개의 평가 지표 반환 가능

#### GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
* Classifier나 Regressor와 같은 알고리즘에 사용되는 하이퍼 파라미터를 순차적으로 입력하면서 편리하게 최적의 파라미터를 도출할 수 있는 방안을 제공

In [15]:
grid_parameters = {'max_depth': [1,2,3],
                   'min_samples_split': [2,3]}

* 총 6회(3x2)에 걸쳐 파라미터를 순차적으로 바꿔서 실행함

In [16]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [19]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
### refit=True가 default임, True면 가장 좋은 파라미터 설정으로 재학습시킴
grid_dtree = GridSearchCV(dtree, param_grid = parameters, cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

* params 칼럼은 수행할 때마다 적용된 하이퍼 파라미터 값  
* 4번에 rank_test_score 칼럼 값이 1이므로 3, 2로 평가한 결과 예측 성능이 1위라는 의미 (5번과 공동 1위)
> 즉 이때의 파라미터가 최적의 하이퍼 파라미터
* 그때의 mean_test_score도 가장 높음
> 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가 평균값

In [20]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


* 최고 성능을 나타낸 하이퍼 파라미터의 값과 그때의 평가 결과값이 각각 best_params_, best_score_ 속성에 기록됨

In [22]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSeatchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도:0.9667
