<a href="https://colab.research.google.com/github/jeongminESAA/ESAA/blob/main/ESAA_HW_9_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [넘파이]

*   선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
*   루프를 사용하지 않아 대량 데이터의 빠른 배열 연산 속도 보장
*   저수준 언어 기반의 호환 API 제공




---

### 넘파이 ndarray 개요
*   넘파이 모듈 임포트, as np를 추가해 약어로 모듈 표현

In [2]:
import numpy as np

*   넘파이 기반 데이터 타입은 ndarray
*   다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능

array() : 다양한 인자를 입력 받아서 ndarray로 변환하는 기능 수행

In [3]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)      #1차원 array, 3개의 데이터

array2 = np.array ([[1,2,3],
                    [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2.shape)      #2차원 array, 2개의 로우와 3개의 칼럼, 6개의 데이터

array3 = np.array ([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3.shape)      #2차원 array, 1개의 로우와 3개의 칼럼, 3개의 데이터

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원



*   리스트 [ ] 는 1차원, 리스트의 리스트 [ [ ] ] 는 2차원




---



### ndarray의 데이터 타입
*   데이터값은 숫자, 문자열, 불 등 모두 가능
*   한 개의 ndarray 객체에는 연산의 특성상 같은 데이터 타입만 가능



In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


*   array2의 경우 숫자형 값 1, 2가 모두 문자열로 변환
*   array3의 경우 int형 1, 2가 모두 float형으로 변환

In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


*   astype() 함수를 이용해 데이터 값의 타입 변경 가능
*   () 안에 인자로 원하는 타입을 문자열로 지정
*   메모리를 더 절약해야 할 때 보통 이용됨



---
###ndarray를 편리하게 생성하기 - arange, zeros, ones
*   특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우에 사용
*   주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


*   arange()는 range()와 유사한 기능, array를 range()로 표현하는 것
*   0부터 함수 인자 값 -1 까지의 값을 순차적으로 ndarray의 데이터 값으로 변환해줌

In [9]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)



*   zeros()는 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
*   ones()는 유사하게 1로 채운 ndarray를 반환
*   dtype을 정해주지 않으면 default로 float64형의 데이터로 채움


---
###ndarray의 차원과 크기를 변경하는 reshape()


*   reshape()는 ndarray를 특정 차원 및 원하는 크기로 변환



In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


*   지정된 사이즈로 변경이 불가능하면 오류 발생

In [11]:
array1.reshape(4,3)

ValueError: ignored



*   -1 을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌



In [12]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)            # 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환하라는 의미
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)




*   마찬가지로 변경이 불가능한 사이즈일 경우 오류 발생




In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: ignored



*   reshape(-1,1)와 같은 형태로 자주 사용
*   ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 반드시 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장



In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


---
###넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)


*   ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 하는 인덱싱


> 1.   특정한 데이터만 추출 : 원하는 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨
2.   슬라이싱(Slicing) : 연속된 인덱스상의 ndarray를 추출, 'a:b' 기호 사용하여 시작 인덱스 a와 종료 인덱스 b-1 까지에 해당하는 ndarray가 반환됨
3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환함
4. 불린 인덱싱(Boolean Indexing) : 특정 조건에 해당하는지 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환함





####단일값 추출

*   한 개의 데이터만을 추출
*   객체에 해당하는 위치의 인덱스 값을 [ ] 안에 입력하면 됨


In [15]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


*   -1 은 맨 뒤의 데이터 값을 의미

In [16]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


* 단일 인덱스를 이용해 ndarray 내의 데이터 값도 간단히 수정 가능

In [17]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]




*   다차원 ndarray에서 단일 값 추출
*   콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근
*   axis 0 은 로우 방향의 축, axis 1 은 칼럼 방향의 축





In [18]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


####슬라이싱

*   ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출, 시작 인덱스~종료 인덱스-1
*   단일 데이터값 추출을 제외한 인덱싱은 ndarray 타입

In [19]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>




1.   ':' 기호 앞에 시작 인덱스 생략 시 자동으로 맨 처음 인덱스인 0으로 간주
2.   ':' 기호 뒤에 종료 인덱스 생략 시 자동으로 맨 마지막 인덱스로 간주
3.   ':' 기호 앞/뒤에 시작/종료 인덱스 생략 시 자동으로 맨 처음/맨 마지막 인덱스로 간주



In [20]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])      # 1~2행, 1~2열
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])      # 2~3행, 1~3열
print('array2d[1:3, :] \n', array2d[1:3, :])          # 2~3행
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])            # 로우나 칼럼 축 한쪽에만 슬라이싱을 적용하고, 다른 쪽 축에는 단일 값 인덱스를 적용해도 됨

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]




*   2차원에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환




In [22]:
print(array2d[0])         # 첫번째 로우 반환
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


####팬시 인덱싱

*   리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]                             # 로우에 팬시 인덱싱인 [0,1], 칼럼에 단일 값 인덱싱 2
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


####불린 인덱싱

*   조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용됨
*   ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 기재하면 됨

In [24]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean Indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]




*   조건에 맞는 데이터가 있는 위치는 True 값이, 그렇지 않은 경우는 False 값이 반환됨



In [25]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [26]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [27]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]



* 불린 인덱스 동작 단계
> 1.   ndarray의 필터링 조건을 [ ] 안에 기재
 2.   False 값은 무시하고 True 값에 해당하는 인덱스 값만 저장
 3.   저장된 인덱스 데이터 세트로 ndarray 조회



---
###행렬의 정렬 - sort()와 argsort()
####행렬 정렬


*   np.sort()는 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
*   ndarray.sort()는 원 행렬 자체를 정렬한 형태로 반환, 반환 값은 None




In [28]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]




*   기본적으로 오름차순으로 행렬 내 원소를 정렬
*   내림차순으로 정렬하기 위해서 [ ::-1 ]을 적용



In [29]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]




*   행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우/칼럼 방향으로 정렬 수행 가능




In [30]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


####정렬된 행렬의 인덱스를 반환하기


*   원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할때 np.argsort() 사용
*   nd.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환


In [31]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]




*   기본 오름차순, 내림차순 정렬 시 동일하게 [::-1]을 적용






In [32]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


* argsort()는 넘파이에서 매우 활용도가 높음
* 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 함
> 예를 들어, 학생별 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 성적을 각각 ndarray로 가져야 함

In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


---
###선형대수 연산 - 행렬 내적과 전치 행렬 구하기
####행렬 내적(행렬 곱)


*   두 행렬 A와 B의 내적은 np.dot()을 이용해 계산 가능
*   왼쪽 행렬의 로우와 오른쪽 행렬의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
*   왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능


In [34]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


####전치 행렬


*   원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
*   A의 전치 행렬은 A^T와 같이 표기함
*   transpose()를 이용해 전치 행렬을 쉽게 구할 수 있음

In [36]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
