<a href="https://colab.research.google.com/github/ujeongmin/ESAA/blob/main/exercises_9_8(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array3 = np.zeros(10)
print(array3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# 내 풀이 print('memory of size:', array3.size * array3.itemsize)

array4 = np.zeros((10,10))
print("%d bytes" % (array4.size * array4.itemsize))

800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array5 = np.zeros(10)
array5[4] = 1
print(array5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array6 = np.arange(10,50)
print(array6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array7 = np.arange(10,50)
array7 = array7[::-1]
print(array7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array8 = np.arange(0,9)
array8.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array9 = np.array([1,2,0,0,4,0])
array9_nonzero = np.nonzero(array9)
print(array9_nonzero)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
array10 = np.identity(3)
print(array10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array11 = np.random.random((3,3,3))
print(array11)

[[[0.4094636  0.27167414 0.27522184]
  [0.24602846 0.59386835 0.01374479]
  [0.85111486 0.31648952 0.92419184]]

 [[0.457565   0.28808488 0.33072759]
  [0.71981148 0.45525285 0.15843157]
  [0.7028794  0.4013094  0.89282653]]

 [[0.77863561 0.80605105 0.65166687]
  [0.07376349 0.7643371  0.95874812]
  [0.60057921 0.43507848 0.56478037]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array12 = np.random.random((10,10))
print(array12)
print('minimum values :', array12.min())
print('maximum values :', array12.max())

[[0.57594127 0.98543173 0.95999185 0.14030145 0.78762055 0.01052814
  0.2062592  0.57709494 0.53756751 0.55185103]
 [0.49506716 0.60576898 0.27163307 0.24686999 0.15274243 0.73495348
  0.35128343 0.73976415 0.27588394 0.74229638]
 [0.78020599 0.96963252 0.02859024 0.27867151 0.54606305 0.10394799
  0.64345435 0.60131504 0.94290636 0.33684332]
 [0.78743349 0.08980754 0.56262486 0.01361111 0.47797512 0.44624499
  0.39691887 0.14749395 0.44518324 0.46696085]
 [0.84755467 0.25252575 0.75435965 0.28228567 0.31674885 0.77672615
  0.64165756 0.49254483 0.45195789 0.009445  ]
 [0.39119435 0.76195188 0.50110003 0.93940193 0.99005605 0.65442584
  0.83026898 0.84077902 0.60866381 0.84237164]
 [0.16948312 0.72155465 0.93204978 0.21622111 0.51766251 0.86022728
  0.97580637 0.78474462 0.23292545 0.70622577]
 [0.3082436  0.76149985 0.54204884 0.48175082 0.28009811 0.73113589
  0.70320422 0.02279453 0.59966749 0.5932322 ]
 [0.15054462 0.37107869 0.04525377 0.00806377 0.99809533 0.24105368
  0.13541252

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array13 = np.random.random(30)
print(array13)
print('mean vaule:', array13.mean())

[0.3142891  0.43989455 0.60315817 0.85041631 0.48087764 0.36200545
 0.19849439 0.49200247 0.51507291 0.2106872  0.15575283 0.5333114
 0.30159882 0.88448226 0.98751931 0.03480501 0.89840247 0.39699751
 0.67601317 0.32613967 0.76881461 0.17094306 0.5935623  0.07954081
 0.33725322 0.80844943 0.02246553 0.71627318 0.0674473  0.26571376]
mean vaule: 0.4497461276349584


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array14 = np.ones((5,5))
array14[1:-1,1:-1]=0
print(array14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)        # 결과 : nan
print(np.nan == np.nan)   # 결과 : False
print(np.inf > np.nan)    # 결과 : False
print(np.nan - np.nan)    # 결과 : nan
print(np.nan in set([np.nan]))    # 결과 : True
print(0.3 == 3 * 0.1)    # 결과 : False

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array16 = np.diag(1+np.arange(4), k=-1)
print(array16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array17 = np.ones((8,8), dtype = int)
array17[1::2,::2] = 0
array17[::2,1::2] = 0     # a:b:c 이면 a와 b는 시작과 끝, c는 간격
print(array17)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
# 내 풀이 print(np.unravel_index(100,(6,7,8)))
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array19 = np.random.random((5,5))
normal = (array19 - np.mean (array19)) / (np.std (array19))
print(normal)

[[-0.28355086  0.19784135  0.46323464 -1.49021727 -1.48238066]
 [ 1.24947217 -0.01769964 -1.45746823  0.7691939  -0.20861201]
 [ 1.73405835  1.69973989  0.81363871 -1.53440173 -0.34914228]
 [-0.70290835  1.60973803 -0.49204657  0.52610297  0.69927151]
 [ 0.5833767   0.10919113 -1.27691522 -0.84827297 -0.31124356]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array21 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(array21)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array22 = np.arange(11)
array22[ ( 3 < array22 ) & ( array22 <= 8 )] *= -1
print(array22)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(9).reshape(3,3)
#legal
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


# Z<Z>Z -> X illegal   < 마지막 것

[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
np.array(0) / np.array(0)   # 결과 : nan
np.array(0) // np.array(0)   # 결과 : 0에 가까운 수
np.array([np.nan]).astype(int).astype(float)    # 결과 : 오

<ipython-input-24-7b6407ad6107>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)   # 결과 : nan
<ipython-input-24-7b6407ad6107>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)   # 결과 : 0에 가까운 수


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [3]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))       # np.intersect1d()를 이용하면 공통 원소 찾을 수 있음

[0 1 2 4]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [26]:
print(np.sqrt(-1))            # nan
print(np.emath.sqrt(-1))      # j는 복소수 i를 의미함

np.sqrt(-1) == np.emath.sqrt(-1)      #False

nan
1j


<ipython-input-26-54fe99ce1398>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))            # nan
<ipython-input-26-54fe99ce1398>:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)      #False


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [32]:
Z = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [33]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)          # A+B의 결과를 B에 할당
np.divide(A,2,out=A)       # A/2의 결과를 A에 할당
np.negative(A,out=A)       # -(A/2)의 결과를 A에 할당
np.multiply(A,B,out=A)     # (A+B)*(-A/2)와 같은 결과

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [7]:
array30 = np.random.uniform(0,10,10)

print(array30 - array30%1)
print(array30 // 1)

[2. 3. 5. 5. 9. 5. 9. 1. 5. 4.]
[2. 3. 5. 5. 9. 5. 9. 1. 5. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
array31 = np.zeros((5,5))         # zeros로 5x5 행렬 만든 다음, np.arange(5) 행을 더해줌
array31 += np.arange(5)
print(array31)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [8]:
array32 = np.random.random(10)
array32.sort()
print(array32)

[0.03207173 0.11885219 0.19778776 0.30712518 0.45697268 0.58319534
 0.7820389  0.82310471 0.88060693 0.99671987]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [9]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)                        # not equal

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [34]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]          # x와 y에 각각 0열, 1열 할당
R = np.sqrt(X**2+Y**2)        # 데카르트 좌표로 표현
T = np.arctan2(Y,X)           # 극좌표계 표현
print(R)
print(T)

[0.68612001 0.46443934 0.65393691 1.00459255 0.80256178 0.64480173
 0.37228161 1.26452518 0.73734782 0.52536763]
[1.06065643 1.2148858  1.07975272 1.0324818  0.49013755 1.03542963
 0.36369864 0.78808343 0.0331978  0.81329702]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [11]:
Z = np.random.random(10)
Z[Z.argmax()] = 0            # 최대값을 찾아 0으로 바꿈
print(Z)

[0.89832716 0.         0.76544072 0.81087088 0.83964789 0.47821359
 0.50317116 0.58017358 0.10178293 0.90482608]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [46]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()       #  가장 가까운 값 = 주어진 값과 벡터의 각 요소를 뺀 값 중 가장 작은 값 찾으면 됨
print(Z)
print(v)
print(index)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
6.135460667317327
6
6


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [23]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [15]:
n = 10
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [19]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])             # z[z[:,1].argsort()]는 열의 두번째(인덱스 1) 성분은 기준으로 정렬한다는 뜻

[[3 0 2]
 [5 2 6]
 [0 6 7]]
[[0 6 7]
 [3 0 2]
 [5 2 6]]


In [20]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 1 7]
 [6 0 5]
 [5 1 4]]
[[6 0 5]
 [8 1 7]
 [5 1 4]]


In [22]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[7 6 7]
 [1 0 5]
 [3 8 2]]
[[3 8 2]
 [1 0 5]
 [7 6 7]]
